version: '2'

services:
  worker:
    # build: ./project
    image: celery:latest
    command: celery -A main worker -l info
    # volumes:
    #   - ./project/:/usr/src/app/
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
    #   - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis

  celery-beat:
    image: celery:latest
    # build: ./project
    command: celery -A main beat -l info
    # volumes:
    #   - ./project/:/usr/src/app/
    depends_on:
      - redis 

  redis:
    container_name: "redis"
    image: docker.io/bitnami/redis:6.2
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
    redis_data:
      driver: local